version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./data/tmp:/tmp/images
    depends_on:
      - milvus
    restart: unless-stopped
    networks:
      - milvus-net

  milvus:
    image: milvusdb/milvus:v2.5.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_CFG_AUTO_COMPACTION_MODE: revision
      ETCD_CFG_AUTO_COMPACTION_RETENTION: "1000"
      COMMON_CFG_RETENTION_DURATION: 0s
    volumes:
      - ./data/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091" # WebUI port
    networks:
      - milvus-net
    restart: unless-stopped

networks:
  milvus-net:
    driver: bridge 